### ISSUE TITLE
undefined method `mattr_accessor'

### ISSUE THREAD

**Issue by Michael-Sivalls** [hempalex/homebrew-formula#1]
when running the ruby script `dklab_realsync.rb` I'm getting an error `<module:Formula>': undefined method `mattr_accessor' for Formula:Module (NoMethodError)

any idea what the issue is here?

**Comment by hempalex** [comment]
Because it's not a ruby file. It's homebrew formula.
Read the docs https://docs.brew.sh/Taps
Use
> brew tap hempalex/homebrew-formula
> brew install dklab_realsync

Then next run just run realsync
> realsync

Please note - i've made it just for my personal use, formula file contains some patches which is intended only for my convenience. Use it as is or make pull request ))
